# Generated by Django 3.2 on 2021-11-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211112_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-datetime']},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='money',
            new_name='amount',
        ),
    ]
